# jn1

In [67]:
import numpy as np
import pandas as pd

import os
#os.sys.path
import sys
sys.path.append('../src')

import cv2
import matplotlib.pyplot as plt
#import src.code1_data as go

In [68]:
df= pd.read_csv("../../PROJECT/data_inputs/inp1/fer2013/fer2013.csv", encoding = "ISO-8859-1")

In [73]:
ruta = "../../PROJECT/data_inputs/inp1/fer2013/fer2013.csv"

In [69]:
emotions= ('Angry','Disgust','Fear','Happy','Sad','Surprise','Neutral')
df['emotion_name']=df.emotion.apply(lambda x: emotions[x])

In [70]:
df.sample(5)

emotion                                             pixels  \
19560        6  1 100 156 146 154 171 182 191 190 191 192 199 ...   
16968        4  59 29 31 28 21 17 26 21 24 41 51 69 80 95 97 7...   
34392        3  235 235 234 235 234 234 235 233 236 212 217 22...   
1829         2  54 48 61 88 123 148 136 154 140 116 136 141 10...   
21803        3  225 232 206 183 170 136 128 132 124 127 151 15...   

             Usage emotion_name  
19560     Training      Neutral  
16968     Training          Sad  
34392  PrivateTest        Happy  
1829      Training         Fear  
21803     Training        Happy

In [71]:
df['jorge'] = df.pixels.copy()

In [82]:
def getData(filname):
    # images are 48x48
    # N = 35887
    Y = []
    X = []
    first = True
    for line in open(filname):
        if first:
            first = False
        else:
            col = line.split(',')
            
            Y.append(int(col[0]))
            X.append([int(p) for p in col[1].split()])

    X, Y = np.array(X) / 255.0, np.array(Y)
    print(Y)
    return X, Y

In [83]:
X,Y=getData(ruta)

[0 0 2 ... 0 3 2]


In [77]:
X

array([[0.2745098 , 0.31372549, 0.32156863, ..., 0.41568627, 0.42745098,
        0.32156863],
       [0.59215686, 0.58823529, 0.57647059, ..., 0.75686275, 0.71764706,
        0.72156863],
       [0.90588235, 0.83137255, 0.61176471, ..., 0.34509804, 0.43137255,
        0.59607843],
       ...,
       [0.06666667, 0.06666667, 0.0627451 , ..., 0.60392157, 0.52156863,
        0.44313725],
       [0.11764706, 0.10980392, 0.10980392, ..., 0.1372549 , 0.11764706,
        0.10980392],
       [0.0745098 , 0.05098039, 0.05490196, ..., 0.74117647, 0.78039216,
        0.78823529]])

In [28]:
df['pixs'] = [[int(num) for num in each.split()] for each in df['pixels']]

In [51]:
df['pixarrs'] = df['pixs'].apply(lambda x: np.asarray(x))

In [54]:
df.pixarrs[1]

array([151, 150, 147, ..., 193, 183, 184])

In [55]:
type(df.pixs[0])

list

In [56]:
type(df.pixarrs[0])

numpy.ndarray

In [59]:
df.pixarrs[0]

array([ 70,  80,  82, ..., 106, 109,  82])